### ISSUE TITLE
Upgrade nomad to 0.8.0

### ISSUE THREAD

**Issue by ThomasObenaus** [MatthiasScholz/cos#10]
Released just a few days ago ... we should upgrade.
Changelog: https://github.com/hashicorp/nomad/blob/v0.8.0/CHANGELOG.md

Interesting improvements:
* core: Servers can now service client HTTP endpoints [GH-3892] ... would solve https://github.com/MatthiasScholz/cos/issues/9
* cli: Node status and filesystem related commands do not require direct network access to the Nomad client nodes [GH-3892]
* ui: All views poll for changes using long-polling via blocking queries [GH-3936]

**Comment by MatthiasScholz** [comment]
# Notes
* discovery: Prevent absolute URLs in check paths. The documentation indicated that absolute URLs are not allowed, but it was not enforced. Absolute URLs in HTTP check paths will now fail to validate. [GH-3685] **-> Check nomad job descriptions.**

**Comment by ThomasObenaus** [comment]
Done with https://github.com/MatthiasScholz/cos/commit/fcac354fa623b03f9eb68248923f76cb48c0e780.
