### ISSUE TITLE
dnsmasq not used for DNS based service-discovery

### ISSUE THREAD

**Issue by ThomasObenaus** [MatthiasScholz/cos#13]
Since not all services support consul based service-discovery, we added dnsmasq on the instances.
As specified at https://www.consul.io/docs/guides/forwarding.html dnsmasq can be used to intercept all queries to the consul domain to 127.0.0.1:8600.
There at 127.0.0.1:8600 the consul-agent is running which is able to provide a service-discovery based on the service-catalog.

*But* dnsmaq is not configured correctly in order to intercept local calls.

**Comment by ThomasObenaus** [comment]
### Reproduce
Log into an instance and there try:
dig prometheus.service.consul

**Comment by ThomasObenaus** [comment]
The configured nameservers 10.128.8.8 resp 10.128.0.2 are used.
dnsmasq is not used at all.

**Comment by ThomasObenaus** [comment]
Explicitly going over dnsmasq works

```dig @localhost prometheus.service.consul```

>; <<>> DiG 9.9.4-RedHat-9.9.4-51.amzn2.2 <<>> @localhost prometheus.service.consul
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25286
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

>;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;prometheus.service.consul.	IN	A

>;; ANSWER SECTION:
prometheus.service.consul. 0	IN	A	10.128.141.119

>;; Query time: 5 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: So Apr 29 18:48:21 UTC 2018
;; MSG SIZE  rcvd: 70

**Comment by ThomasObenaus** [comment]
*Hack* 
Adding ```127.0.0.1``` (by hand) to the /etc/resolv.conf works at least on the host, but not from inside the docker container.

**Comment by MatthiasScholz** [comment]
Docker run has to be configured to use the local DNS.

Thomas Obenaus <notifications@github.com> schrieb am So., 29. Apr. 2018,
20:51:

**Comment by MatthiasScholz** [comment]
Please verify, because then the issue can be closed.

Is this related somehow to the consul nodes not being configured as DNS?

**Comment by ThomasObenaus** [comment]
@MatthiasScholz: Correct, the solution is to specify with the docker run command to use the local DNS (dnsmasq in this case).

--> Close ticket.
