### ISSUE TITLE
Prometheus can't scrape metrics from nomad-clients

### ISSUE THREAD

**Issue by ThomasObenaus** [MatthiasScholz/cos#14]
Reason the SG on the clients does not allow inbound on 4646

**Comment by MatthiasScholz** [comment]
It means then the backoffice has to know about all other datacenters or the backoffice nodes have to be attached to all other datacenters - means new input parameter.

**Comment by MatthiasScholz** [comment]
Was already solved with the following commit: e660735992310a5e1c3582b52c93cb482e96b7ed.
