### ISSUE TITLE
Nomad UI LogMessage Visibility

### ISSUE THREAD

**Issue by MatthiasScholz** [MatthiasScholz/cos#35]
Using the nomad ui and trying to examine the logs for one allocation just gives empty results for stdout and stderr:
* [Nomad UI Reviewing Logs](https://www.nomadproject.io/guides/ui.html#reviewing-logs)

**Comment by ThomasObenaus** [comment]
Fixed with ef827d0b045c79988aff4a3076da5db5b2a17f20.
There the ports 4646-4647 (tcp) between the clients where opened.

**Comment by ThomasObenaus** [comment]
The work was done with bug #28.

**Comment by ThomasObenaus** [comment]
See:
![log_ping_service](https://user-images.githubusercontent.com/1695514/46914446-088c6080-cf9e-11e8-8336-81b34306ccf8.png)

**Comment by ThomasObenaus** [comment]
Note: When a logdriver like fluentd is used to ship away the stdout + stderr there will be no logs visible in the ui.
Instead a message like `log entry for task "XYZ" and log type "stderr" not found` will appear.
