### ISSUE TITLE
Update to v0.4.4 of consul module

### ISSUE THREAD

**Issue by ThomasObenaus** [MatthiasScholz/cos#40]
Update the infrastructure module for consul using the newest version [v0.4.4](https://github.com/hashicorp/terraform-aws-consul/tree/v0.4.4).
This includes breaking changes in their API.

**Comment by ThomasObenaus** [comment]
Tested with root-example and deployment of fabio and ping-service

**Comment by MatthiasScholz** [comment]
Issue resolved with #42
