### ISSUE TITLE
Move to terraform 0.12

### ISSUE THREAD

**Issue by ThomasObenaus** [MatthiasScholz/cos#70]
Terraform 0.12 is now out for a while (current version is 0.12.9). Since it contains breaking changes in the HCL the code of the COS has to be adjusted to it.

As a precondition the referenced modules have to be terraform 0.12 compatible as well
* [terrafrom-aws-nomad at v0.5.0](https://github.com/hashicorp/terraform-aws-nomad/tree/v0.5.0) is compatible
* [terraform-aws-consul at v0.7.0](https://github.com/hashicorp/terraform-aws-consul/releases/tag/v0.7.0) is compatible

**Comment by MatthiasScholz** [comment]
Changes are merged. Issue solved.
